# ***************************** Lista de Materias***********************************

Subject.create([
        
         # -------------------------------------- CIENCIAS ECONOMICAS ------------------------------------
        
        #Administración de empresas
        {code: 25200001, name: 'Formación Básica', credits: -2},
        {code: 25200002, name: 'Estadística y Probabilidad fundamental', credits: -2}, 
        {code: 25200003, name: 'Econometría(sugerida)', credits: -2},
        {code: 25200004, name: 'Interdisciplinar 1', credits: -2},
        {code: 25200005, name: 'Interdisciplinar 2', credits: -2},
        {code: 25200006, name: 'Interdisciplinar 3', credits: -2},
            {code: 2016123, name: 'instituciones politico-constitucionales colombianas', credits: 4},
            {code: 2016043, name: 'Matemáticas financieras', credits: 4},
            {code: 1000015, name: 'Probabilidad fundamental', credits: 3},
            {code: 1000016, name: 'Inferencia estadística fundamental', credits: 3},
            {code: 2016125, name: 'Métodos cuantitativos', credits: 4},
            {code: 2016119, name: 'Derecho internacional', credits: 3},
            {code: 2016124, name: 'Investigación operativa', credits: 3},
            {code: 2016126, name: 'Planeación estratégica', credits: 3},
            {code: 2015411, name: 'Tipos modernos de contratación', credits: 3},
            {code: 2016358, name: 'Gerencia de recursos humanos', credits: 3},
            {code: 2016587, name: 'Competitividad, productividad y benchmarking', credits: 3},
            {code: 2017865, name: 'Desarrollo humano en el trabajo', credits: 3},
            {code: 2017872, name: 'Entrevista psicológica', credits: 3},
            {code: 2017911, name: 'Psicología organizacional', credits: 3},
            {code: 2021835, name: 'Investigación de mercados', credits: 3},
            {code: 2006824, name: 'Contabilidad de inversiones y financiación', credits: 4},
            {code: 2006838, name: 'Control interno y gestion', credits: 3},
            {code: 2006871, name: 'Investigación operativa', credits: 3},
            {code: 2006926, name: 'Planeación estratégica', credits: 4},
            {code: 2006966, name: 'Pensamiento económico', credits: 4},
            {code: 2019594, name: 'Microeconomía ii', credits: 3},
            {code: 2022104, name: 'Asignatura genérica', credits: 3},
            {code: 2023780, name: 'Macroeconomía ii', credits: 4},
            {code: 2006973, name: 'Economía política i', credits: 3},
            {code: 2006979, name: 'Microeconomía ii', credits: 4},
            
            
        #Economia
        {code: 25220001, name: 'Contenido cuantitativo', credits: -2},
        {code: 25220002, name: 'Interdisciplinar - profesional 1', credits: -2},
        {code: 25220003, name: 'Interdisciplinar - profesional 2', credits: -2},
        {code: 25220004, name: 'Interdisciplinar - profesional 3', credits: -2},
        {code: 25220005, name: 'Interdisciplinar - profesional 4', credits: -2},
            {code: 2016000, name: 'derecho finaciero', credits: 3},
            {code: 2016027, name: 'derecho laboral', credits: 4},
            {code: 2016030, name: 'economía dinámica en matlab', credits: 3},
            {code: 2016031, name: 'economía evolucionista y herramientas de simulación', credits: 3},
            {code: 2016034, name: 'economía y política social', credits: 3},
            {code: 2016035, name: 'estado y descentralización', credits: 3},
            {code: 2016040, name: 'gestión y política pública', credits: 3},
            {code: 2016043, name: 'matemáticas financieras', credits: 4},
            {code: 2016044, name: 'mercadeo internacional', credits: 3},
            {code: 2016045, name: 'mercado de capitales y banca de inversión', credits: 3},
            {code: 2016047, name: 'modelos económicos computacionales', credits: 3},
            {code: 2016048, name: 'nueva economía política', credits: 3},
            {code: 2016049, name: 'política fiscal avanzada', credits: 3},
            {code: 2016050, name: 'seminario de gestión de negocios internacionales', credits: 3},
            {code: 2016051, name: 'seminario de historia económica de colombia', credits: 3},
            {code: 2016052, name: 'sistema monetario y crisis financiera internacional', credits: 3},
            {code: 2016054, name: 'tópicos de econometría ii', credits: 3},
            {code: 2016055, name: 'tópicos de econometría i', credits: 3},
            {code: 2016109, name: 'programación dinámica', credits: 3},
            {code: 2018392, name: 'economia del conocimiento o nueva economia', credits: 3},
            {code: 2021788, name: 'evaluacion economica y social de proyectos', credits: 3},
            {code: 2024037, name: 'estructuras de mercado y competencia perfecta en la historia del pensamiento economico', credits: 3},
            {code: 2024267, name: 'globalización e integración con énfasis en asia pacifico', credits: 3},
            {code: 2024564, name: 'econometria financiera', credits: 3},
            {code: 2024565, name: 'regulacion y mercados', credits: 3},
            {code: 2024566, name: 'evaluacion economica y social de proyectos', credits: 3},
            {code: 2024567, name: 'economia, politica y conflicto', credits: 3},
            {code: 2024569, name: 'aplicaciones empíricas de la teoría del consumidor', credits: 3},
            {code: 2024572, name: 'topicos de politica publica', credits: 3},
            {code: 2024575, name: 'keynesian economics', credits: 3},
            {code: 2024595, name: 'historia economica de america latina', credits: 3},
            {code: 2024665, name: 'dinero y mercados financieros', credits: 3},
            {code: 2024666, name: 'integracion y bloques economicos', credits: 3},
            {code: 2024667, name: 'economia y política de la sostenibilidad', credits: 3},
            {code: 2024653, name: 'alternativas al desarrollo', credits: 3},
            {code: 2024568, name: 'ciclos economicos', credits: 3},
            {code: 2024570, name: 'economia de los grupos economicos ii', credits: 3},
            {code: 2024571, name: 'seminario economia constitucional', credits: 3},
            {code: 2024573, name: 'ocupacion, empleo y seguridad social', credits: 3},
            {code: 2024574, name: 'internacionalizacion y cambio estructural', credits: 3},
            {code: 2024576, name: 'financiarizacion en la economia mundial', credits: 3},
            {code: 2024577, name: 'desarrollo economia y libertad', credits: 3},
            {code: 2024578, name: 'fundamentos de teoría económica ambiental', credits: 3},
            {code: 2024579, name: 'la ciudad: reflexiones socioeconomicas sobre la espacialidad urbana', credits: 3},
            {code: 2024596, name: 'economia de los grupos economicos', credits: 3},
            
            
            
            
        # -------------------------------------- CIENCIAS  ------------------------------------
        
        #Ciencias de la computación
        {code: 29330001, name: 'Física', credits: -2},
            {code: 2022689, name: 'Fundamentos de fisica', credits: 3},
        {code: 29330002, name: 'Criptografía e información', credits: -2},
            {code: 2027311, name: 'Introducción a la criptografía y a la teoría de información', credits: 3},
            {code: 2027310, name: 'Criptografía', credits: 3},
        {code: 29330003, name: 'Analisis númerico y mátematica aplicada', credits: -2},
            {code: 2027628, name: 'Teoría de lenguajes formales', credits: 3},
            {code: 2019267, name: 'Teoría de la recursión', credits: 3},
            {code: 2021834, name: 'Informática aplicada', credits: 3},
            {code: 2024065, name: 'Mundos Virtuales', credits: 3},
        {code: 29330004, name: 'Computación cientifica', credits: -2},
            {code: 2015173, name: 'Introducción a la optimización', credits: 4},
            {code: 2027630, name: 'Introducción al modelamiento matemático', credits: 3},
        {code: 29330005, name: 'Computación aplicada', credits: -2},
            {code: 2027641, name: 'Análisis de bases de datos', credits: 3},
            {code: 2025196, name: 'Introducción a la biología computacional', credits: 4},
            {code: 2027631, name: 'Introducción a la inteligencia artificial', credits: 3},
            {code: 2027309, name: 'Análisis forense digital', credits: 4},
            {code: 2027632, name: 'Física computacional', credits: 3},
            {code: 2027643, name: 'Introducción al aprendizaje de máquina', credits: 3},
            {code: 2016740, name: 'Finanzas Computacionales', credits: 4},
        
        #Matematicas
        {code: 25180001, name: 'Geometria', credits: -2},
            {code: 2015172, name: 'Geometría elemental', credits: 4},
            {code: 1000008, name: 'Geometria Vectorial y Analítica', credits: 4},
        {code: 25180002, name: 'Física', credits: -2},    
            {code: 2015170, name: 'Fundamentos de oscilaciones, ondas y óptica', credits: 4},
            {code: 2015169, name: 'Fundamentos de mecánica de fluidos', credits: 3},
            {code: 2015167, name: 'Fundamentos de física moderna', credits: 3},
        {code: 25180003, name: 'Disciplinar 1', credits: -2},
        {code: 25180004, name: 'Disciplinar 2', credits: -2},
        {code: 25180005, name: 'Disciplinar 3', credits: -2},
            {code: 2015160, name: 'Algebra conmutativa', credits: 4}, 
            {code: 2015179, name: 'Procesos estocásticos', credits: 4},
            {code: 2015161, name: 'Análisis estocástico', credits: 4},
            {code: 2015164, name: 'Ecuaciones diferenciales parciales', credits: 4},
            {code: 2015165, name: 'Epistemología e historia de la matemática', credits: 4},
            {code: 2015171, name: 'Geometría diferencial', credits: 4},
            {code: 2015177, name: 'Modelos matemáticos', credits: 4},
            {code: 2015182, name: 'Teoria de conjuntos', credits: 4},
            {code: 2015183, name: 'Teoría de ecuaciones diferenciales ordinarias', credits: 4},
            {code: 2015185, name: 'Teoría de modelos', credits: 4},
            {code: 2015186, name: 'Teoría de números', credits: 4},
            {code: 2025580, name: 'Anillos y módulos', credits: 4},
        
        #Fisica
        {code: 25160001, name: 'Formación integral humanistica y en ciencia y tecnología', credits: -2},
        {code: 25160004, name: 'Formación integral humanistica y en ciencia y tecnología', credits: -2},
            {code: 2000420, name: 'Humanidades ii', credits: 3},
            {code: 2000447, name: 'Galileo y Newton', credits: 3},
            {code: 2000449, name: 'Ciencia tecnologia y desarrollo', credits: 3},
            {code: 2000904, name: 'Computación, algoritmos estructuras de datos', credits: 3},
            {code: 2000906, name: 'Matematicas financiera', credits: 3},
            {code: 2000907, name: 'Matematica financiera para no matematicos', credits: 3},
            {code: 2000929, name: 'Analisis i', credits: 4},
            {code: 2000939, name: 'Matematicas discretas', credits: 3},
            {code: 2000950, name: 'Geometria elemental', credits: 4},
            {code: 2001839, name: 'Programación de computadores', credits: 3},
            {code: 2003230, name: 'Colombia arte y cultura', credits: 3},
            {code: 2003646, name: 'Introducción a la modernidad: reforma', credits: 3},
            {code: 2005271, name: 'Principios básicos del derecho para estudiantes de otras carreras', credits: 3},
            {code: 2005974, name: 'Seminario de filosofia y pensamiento politico latinoamericano', credits: 3},
            {code: 2006290, name: 'Etica profesional', credits: 3},
            {code: 2006967, name: 'Microeconomia i', credits: 4},
            {code: 2007735, name: 'Cultivos transgenicos: ¿frankenstein o prometeo?', credits: 3},
            {code: 2007773, name: 'Japones electivo iii', credits: 3},
            {code: 2009065, name: 'Platon', credits: 3},
            {code: 2012273, name: 'America latina en el nuevo orden internacional', credits: 3},
            {code: 2012421, name: 'Aproximaciones al habitad popular reflexión y acción para el mejoramiento de la vivienda', credits: 3},
            {code: 2012589, name: 'Introducción a los bionegocios y a las empresas de innovación tecnologica', credits: 3},
            {code: 2014181, name: 'Catedra augusto angel', credits: 3},
            {code: 2014307, name: 'Biofisica celular', credits: 4},
            {code: 2014485, name: 'Catedra de creación - facultad de artes', credits: 3},
            {code: 2014651, name: 'Música y cultura', credits: 3},
            {code: 2014735, name: 'catedra manuel ancizar la educ sup: tend, debates y retos para el siglo xxi. sosten y financiacieras', credits: 3},
            {code: 2014928, name: 'solucion de problemas prioritarios con tecnologias de bajo costo', credits: 3},
            {code: 2001434, name: 'astronomia general i', credits: 3},
            {code: 2001435, name: 'astronomia general ii', credits: 3},
            {code: 2001456, name: 'museos', credits: 3},
            {code: 2001487, name: 'astronomia para todos', credits: 3},
            {code: 2001769, name: 'la energia en colombia', credits: 3},
            {code: 2001770, name: 'energias no convencionales', credits: 3},
            {code: 2002602, name: 'origami', credits: 3},
            {code: 2003164, name: 'ciudad terrritorio y complejidad', credits: 3},
            {code: 2003261, name: 'musica y sociedad', credits: 3},
            {code: 2004596, name: 'cerebro y comportamiento', credits: 3},
            {code: 2004680, name: 'proceso fundamental psicoanalisis', credits: 6},
            {code: 2005756, name: 'filosofia i: vitalismo cosmico', credits: 3},
            {code: 2006106, name: 'deporte', credits: 3},
            {code: 2007284, name: 'catedra emblematica jose granes-grandes corrientes de la matematica en el siglo xx', credits: 3},
            {code: 2007293, name: 'todo lo que usted quiere saber de genetica y nunca se atrevio a preguntar', credits: 3},
            {code: 2009475, name: 'historia antigua: historia de la guerra en la antigüedad', credits: 3},
            {code: 2010144, name: 'amazonia y otras selvas humedas ecuatoriales, ocupacion y conflicto', credits:3 },
            {code: 2010246, name: 'espacio y territorio: retos en la reconstruccion de la nacion', credits: 3},
            {code: 2010303, name: 'television (contexto)', credits: 3},
            {code: 2011225, name: 'geografia de colombia: espacio y territorio', credits: 3},
            {code: 2011230, name: 'escribir para ser. autoras hispanoamericanas del siglo xx', credits: 3},
            {code: 2011231, name: 'introduccion a la tecnologia nuclear', credits: 3},
            {code: 2011254, name: 'el habitat el entorno de lo urbano la salud y la vivienda', credits: 3},
            {code: 2012248, name: 'modelos pedagogicos en ingenieria', credits: 3},
            {code: 2012639, name: 'galileo', credits: 3},
            {code: 2013126, name: 'ingenieria tecnologia y sociedad', credits: 3},
            {code: 2013646, name: 'derecho indigena biodiversidad y cultura', credits: 3},
            {code: 2013702, name: 'albert einstein creador de universos: pensamiento y obra la epoca y su legado', credits: 3},
            {code: 2013810, name: 'catedra manuel ancizar: los derechos de los niños y las niñas', credits: 3},
            {code: 2013813, name: 'historia, politica y constitucion: la fallida construccion de la nacion en colombia', credits: 3},
            {code: 2014174, name: 'cuantica para todos y para todo', credits: 3},
            {code: 2014484, name: 'catedra de facultades "intersecciones"', credits: 3},
            {code: 2014499, name: 'derecho, poscolonialidad y colonialidad del poder', credits: 3},
            {code: 2014510, name: 'catedra manuel ancizar: desplazamiento forzado en colombia', credits: 3},
            {code: 2014511, name: 'catedra jorge eliecer gaitan: tierra y conflicto', credits: 3},
            {code: 2014734, name: 'catedra jorge eliecer gaitan: colombia en la globalizacion: dinamicas y perspectivas', credits: 3},
            {code: 2015800, name: 'estructura de la sociedad moderna i', credits: 3},
            {code: 2015979, name: 'análisis del discurso i', credits: 3},
            {code: 2016073, name: 'herencias - una mirada a la historia de las artes', credits: 3},
            {code: 2016131, name: 'apreciación musical', credits: 3},
            {code: 2016139, name: 'música y sociedad en colombia', credits: 3},
            {code: 2016383, name: 'introducción a la literatura', credits: 3},
            {code: 2016869, name: 'dibujo i', credits: 3},
            {code: 2016919, name: 'taller gramática del arte', credits: 3},
            {code: 2016920, name: 'historia del arte i', credits: 3},
            {code: 2016924, name: 'introducción a la pintura', credits: 3},
            {code: 2016950, name: 'dramaturgia i', credits: 3},
            {code: 2016992, name: 'teoría e historia medios audiovisuales i', credits: 3},
            {code: 2017002, name: 'narrativa i', credits: 3},
            {code: 2017648, name: 'lógica i', credits: 4},
            {code: 2018121, name: 'música tradicional colombiana', credits: 2},
            {code: 2018123, name: 'música y mito clásico', credits: 2},
            {code: 2018150, name: 'teoría musical i', credits: 3},
            {code: 2024747, name: 'lógica i', credits: 4},
            {code: 2000029, name: 'percepcion y apreciacion de la vida silvestre', credits: 3},
            {code: 2000030, name: 'biología del comportamiento animal y humano', credits: 3},
            {code: 2000245, name: 'coro universitario', credits: 4},
            {code: 2002422, name: 'narracion grafica', credits: 3},
            {code: 2003140, name: 'lengua inga', credits: 3},
            {code: 2003203, name: 'apreciacion musical', credits: 3},
            {code: 2003212, name: 'siglo xx - arte musica e ideas', credits: 3},
            {code: 2003259, name: 'mundos virtuales', credits: 3},
            {code: 2004298, name: 'curso filosofia moderna', credits: 3},
            {code: 2006925, name: 'historia critica del pensamiento colombiano', credits: 3},
            {code: 2006943, name: 'teoria politica', credits: 3},
            {code: 2006956, name: 'conocimiento y conflicto', credits: 3},
            {code: 2007794, name: 'la clínica del caso', credits: 3},
            {code: 2011056, name: 'mecanica cuantica desde un punto de vista informatico', credits: 5},
            {code: 2011229, name: 'educacion, sociedad y cultura', credits: 3},
            {code: 2013809, name: 'catedra jorge eliecer gaitan: pluralismo, legitimidad y economia politica', credits: 3},
            {code: 2014157, name: 'oceanologia general', credits: 4},
            {code: 2014645, name: 'introduccion a los indicadores economicos-sociales para estudiar las ciudades', credits: 3},
            {code: 2014907, name: 'pensamiento politico de marx: escritos de juventud', credits: 3},
            {code: 2014629, name: '¿quienes son los estudiantes de la universidad nacional?', credits: 3},
            {code: 2000416, name: 'humanidades i', credits: 3},
            {code: 2000622, name: 'oceanografia geologica', credits: 3},
            {code: 2000627, name: 'clima y diversidad de clima de colombia', credits: 3},
            {code: 2001599, name: 'seminario del sector de energia', credits: 3},
            {code: 2002983, name: 'fundamentos de teoria del color', credits: 3},
            {code: 2003039, name: 'expresion grafica', credits: 3},
            {code: 2004211, name: 'imagen y sonido', credits: 2},
            {code: 2004445, name: 'ciencia tecnologia y sociedad', credits: 3},
            {code: 2004900, name: 'colombia en la globalizacion', credits: 3},
            {code: 2005292, name: 'bogota: administracion y politicas publicas', credits: 3},
            {code: 2005487, name: 'reflexiones entorno al proceso de envejecimiento', credits: 3},
            {code: 2007731, name: 'empirismo y fisica racional en la inglaterra del siglo xvii: boyle y newton', credits: 3},
            {code: 2010235, name: 'catedra manuel ancizar bases biologicas del comportamiento animal y humano', credits: 3},
            {code: 2011172, name: 'cátedra jorge eliécer gaitán: mataron a gaitán', credits: 3},
            {code: 2011256, name: 'acceso a recursos geneticos: aspectos tecnicos y juridicos', credits: 3},
            {code: 2012245, name: 'las costas maritimas: una aproximacion geologica de las costas colombianas', credits: 3},
            {code: 2013124, name: 'teoria politica para no politologos', credits: 3},
            {code: 2014487, name: 'introduccion a los estudios urbanos', credits: 3},
        {code: 25160002, name: 'Estadística', credits: -2},
            {code: 1000015, name: 'Probabilidad fundamental', credits: 3},
        {code: 25160003, name: 'Programación y metodos numéricos', credits: -2},
            {code: 2016652, name: 'Programación e introducción a los métodos numéricos', credits: 3},
        {code: 25160005, name: 'Electrónica e instrumentación', credits: -2},
            {code: 2016683, name: 'Electrónica analógica', credits: 3},
            {code: 2016684, name: 'Electrónica Digital', credits: 3},
        {code: 25160006, name: 'Herramientas matemáticas y computacionales', credits: -2},
            {code: 2016662, name: 'Introducción a los espacios de Hilbert', credits: 3},
            {code: 2016661, name: 'Herramientas computacionales', credits: 3},
        {code: 25160007, name: 'Fluidos y óptica', credits: -2},
            {code: 2016656, name: 'Elasticidad y fluidos', credits: 3},
            {code: 2016660, name: 'Fundamentos de Óptica', credits: 3},
        {code: 25160008, name: 'Aplicaciones de física moderna', credits: -2},
            {code: 2016664, name: 'Técnicas de caracterización A', credits: 3},
            {code: 2016692, name: 'Técnicas de caracterización B', credits: 3},
        {code: 25160009, name: 'Introducción a la investigación', credits: 3},
            {code: 2016670, name: 'Introducción a la investigación teórica', credits: 3},
            {code: 2016669, name: 'Introducción a la investigación experimental', credits: 3},

        #Biología
        {code: 25130001, name: 'Optativa de fundamentación', credits: -2},
        {code: 25130002, name: 'Optativa de fundamentación', credits: -2},
        {code: 25130003, name: 'Optativa de fundamentación', credits: -2},
            {code: 2015238, name: 'geografía física', credits: 4},
            {code: 2016343, name: 'español funcional', credits: 3},
            {code: 2016365, name: 'estadística descriptiva multivariada', credits: 4},
            {code: 2017780, name: 'historia del pensamiento biológico', credits: 2},
            {code: 2017804, name: 'etología', credits: 3},
            {code: 2023215, name: 'geología general', credits: 4},
            {code: 2015244, name: 'geología general', credits: 3},
            {code: 2015250, name: 'introducción al trabajo científico', credits: 3},
            {code: 2015516, name: 'climatología', credits: 3},
            {code: 2015542, name: 'introduccion a la economia', credits: 3},
            {code: 2017771, name: 'análisis y modelación de sistemas biológicos', credits: 3},
            {code: 2017783, name: 'biogeografía', credits: 3},
        {code: 25130004, name: 'Optativa disciplinar', credits: -2},
        {code: 25130005, name: 'Optativa disciplinar', credits: -2},
        {code: 25130006, name: 'Optativa disciplinar', credits: -2},
        {code: 25130007, name: 'Optativa disciplinar', credits: -2},
        {code: 25130008, name: 'Optativa disciplinar', credits: -2},
        {code: 25130009, name: 'Optativa disciplinar', credits: -2},
        {code: 25130010, name: 'Optativa disciplinar', credits: -2},
        {code: 25130011, name: 'Optativa disciplinar', credits: -2},
        {code: 25130012, name: 'Optativa disciplinar', credits: -2},
        {code: 25130013, name: 'Optativa disciplinar', credits: -2},
        {code: 25130014, name: 'Optativa disciplinar', credits: -2},
        {code: 25130015, name: 'Optativa disciplinar', credits: -2},
        {code: 25130016, name: 'Optativa disciplinar', credits: -2},
        {code: 25130017, name: 'Optativa disciplinar', credits: -2},
            {code: 2015226, name: 'cartografía temática', credits: 3},
            {code: 2015233, name: 'fotointerpretación', credits: 3},
            {code: 2016329, name: 'muestreo en poblaciones biológicas', credits: 3},
            {code: 2017516, name: 'artrópodos', credits: 4},
            {code: 2017517, name: 'fisiología animal', credits: 4},
            {code: 2017518, name: 'taxonomía animal', credits: 4},
            {code: 2017781, name: 'análisis multivariante', credits: 3},
            {code: 2026824, name: 'fundamentos de ecologia del paisaje', credits: 4},
            {code: 2017519, name: 'vertebrados', credits: 4},
            {code: 2017522, name: 'biología celular', credits: 4},
            {code: 2017523, name: 'biología molecular', credits: 4},
            {code: 2017524, name: 'biología del desarrollo', credits: 4},
            {code: 2017525, name: 'ecología de ecosistemas y paisajes', credits: 4},
            {code: 2017526, name: 'ecología de poblaciones y comunidades', credits: 4},
            {code: 2017527, name: 'ecología regional continental', credits: 4},
            {code: 2017528, name: 'evolución', credits: 4},
            {code: 2017529, name: 'fundamentos de biología y ecología marina', credits: 4},
            {code: 2017530, name: 'genética de poblaciones', credits: 4},
            {code: 2017531, name: 'inmunología celular y molecular', credits: 4},
            {code: 2017532, name: 'limnología', credits: 4},
            {code: 2017533, name: 'biología de hongos y líquenes', credits: 3},
            {code: 2017534, name: 'biología de protistos y algas', credits: 3},
            {code: 2017535, name: 'diseño experimental', credits: 4},
            {code: 2017537, name: 'espermatófitos', credits: 4},
            {code: 2017536, name: 'embriófitos basales', credits: 3},
            {code: 2017538, name: 'fisiología vegetal', credits: 4},
            {code: 2017539, name: 'formulación y gerencia de proyectos', credits: 2},
            {code: 2017540, name: 'gestión de proyectos', credits: 4},
            {code: 2017541, name: 'introducción a la biología de la conservación', credits: 3},
            {code: 2017544, name: 'política y legislación de recursos naturales', credits: 2},
            {code: 2017546, name: 'taxonomía de angiospermas', credits: 4},
            {code: 2017542, name: 'metodología de la investigación científica', credits: 2},
            {code: 2017543, name: 'microbiología', credits: 4},
            {code: 2017545, name: 'sistemática biológica', credits: 3},
            {code: 2017792, name: 'conservación genética', credits: 3},
            {code: 2017806, name: 'fisiología del crecimiento y desarrollo vegetal', credits: 3},
            {code: 2017808, name: 'floristica y fitogeografía', credits: 3},
            {code: 2017817, name: 'histología animal', credits: 3},
            {code: 2017819, name: 'ictiologia: la biología de los peces', credits: 2},
            {code: 2017827, name: 'introducción a la vegetación de colombia', credits: 3},
            {code: 2017833, name: 'métodos en conservación y manejo de vida silvestre', credits: 3},
            {code: 2017837, name: 'ornitología', credits: 3},
            {code: 2017842, name: 'relaciones ecofisiológicas planta suelo agua', credits: 3},
            {code: 2017845, name: 'tecnicas en biologia molecular', credits: 3},
            {code: 2023212, name: 'análisis y diseño de experimentos', credits: 4},
            {code: 2024393, name: 'formulación y gerencia de proyectos', credits: 4},
            {code: 2025432, name: 'biología de reptiles escamados', credits: 3},
            {code: 2025433, name: 'fisiología animal de sistemas', credits: 4},
            {code: 2025434, name: 'mastozoología general', credits: 3},
            {code: 2026821, name: 'fundamentos de ecologia de comunidades', credits: 4},
            {code: 2026822, name: 'fundamentos de ecologia de ecosistemas', credits: 4},
            {code: 2026823, name: 'fundamentos de ecologia de poblaciones', credits: 4},
 
         # -------------------------------------- INGENIERÍA   ------------------------------------
        #Ingeniería mecatronica
        {code: 25480001, name: 'Física', credits: -2},
            {code: 1000018, name: 'Fundamentos de física moderna', credits: 3},
        {code: 25480002, name: 'Procesos de Manufactura', credits: -2},
        {code: 25480003, name: 'Herramientas para ingeniería', credits: -2},
            {code: 2015942, name: 'Aplicaciones de elementos finitos', credits: 3},
        {code: 25480004, name: 'Ciencias económicas y administrativas', credits: -2},
        {code: 25480005, name: 'Herramientas para automatización de procesos', credits: -2},
            {code: 2022888, name: 'Técnicas de control', credits: 3},
            {code: 2017290, name: 'Técnicas de Inteligencia Artificial', credits: 3},
            
        #Ingeniería quimica
        {code: 25490002, name: 'Informatica y comunicación', credits: -2},
            {code: 2015709, name: 'Comunicación Oral y Escrita', credits: 3},
        {code: 25490003, name: 'Termodinámica', credits: -2},
            {code: 2015738, name: 'Termodinámica de Ciclos', credits: 3},
            {code: 2015739, name: 'Termodinámica molecular', credits: 3},
        {code: 25490004, name: 'Simulación', credits: -2},
            {code: 2015728, name: 'Modelamiento y Simulación de Procesos Bioquímicos', credits: 3},
            {code: 2015729, name: 'Modelamiento y simulación de procesos químicos', credits: 3},
        {code: 25490005, name: 'Materiales', credits: -2},
            {code: 2015717, name: 'Introducción a la ingeniería de materiales', credits: 3},
            {code: 2015724, name: 'Laboratorio de operaciones unitarias ii', credits: 3},
            {code: 2015727, name: 'Materiales', credits: 3},
            {code: 2015730, name: 'Nuevos tópicos en ingeniería quimica', credits: 3},
            {code: 2024929, name: 'Introducción a la ingeniería de materiales poliméricos', credits: 3},
            {code: 2015598, name: 'Química de Sólidos', credits: 3},
            {code: 2001798, name: 'Procesos quimicos i', credits: 3},
        {code: 25490001, name: 'Administración de empresas', credits: -2},
            {code: 2015694, name: 'Derecho laboral', credits: 3},
            {code: 2015698, name: 'Administración de empresas', credits: 3},
            {code: 2015699, name: 'Administración de mercados', credits: 3},
            {code: 2015700, name: 'Fundamentos de contabilidad financiera', credits: 3},
            {code: 2015704, name: 'Mercadeo internacional', credits: 3},
            {code: 2015705, name: 'Mercados I', credits: 4},
            
        # -------------------------------------- MEDICINA   ------------------------------------    
        
        #Fisioterapia
        {code: 25500001, name: 'Biologia', credits: -2},
        {code: 25500002, name: 'Quimica', credits: -2},
        {code: 25500003, name: 'Ciencias sociales y humanas', credits: -2},
        {code: 25500004, name: 'Ciencias sociales y humanas', credits: -2},
            {code: 2017502, name: 'Procesos comunitarios', credits: 3},
            {code: 2017903, name: 'Psicología Comunitaria', credits: 3},
            {code: 2017914, name: 'Psicología y Salud Ocupacional', credits: 3},
            {code: 2024774, name: 'Medicina Social y Salud Colectiva: fundamentos conceptuales', credits: 3},
        {code: 25500005, name: 'Optativa profesional', credits: -2},
            {code: 2016242, name: 'Epidemiología social', credits: 2},
            {code: 2016263, name: 'Mi cuerpo, sus cuerpos, nuestros cuerpos', credits: 2},
            {code: 2016289, name: 'Manejo del dolor', credits: 2},
            {code: 2016292, name: 'Música y bienestar ocupacional', credits: 2},
            {code: 2016294, name: 'Potenciales evocados', credits: 3},
            {code: 2016296, name: 'Reflexiones entorno al proceso de envejecimiento', credits: 3},
            {code: 2016298, name: 'Bioseguridad', credits: 2},
            {code: 2016300, name: 'Investigación biomédica y social', credits: 3},
            {code: 2017939, name: 'Primeros auxilios', credits: 2},
            {code: 2021165, name: 'Ingenieria tisular', credits: 2},
            {code: 2022175, name: 'Cuerpo e imagen', credits: 3},
            {code: 2022733, name: 'Iniciacion a estudios feministas y de género', credits: 3},
            {code: 2022841, name: 'Fundamentación y practica en salud de los trabajadores', credits: 4},
            {code: 2023478, name: 'Contexto bioseguridad', credits: 2},
        {code: 25500006, name: 'Optativa de profundización I', credits: -2},
            {code: 2016221, name: 'Actividad física y deporte I', credits: 2},
            {code: 2016254, name: 'Comunidad y desarrollo humano I', credits: 2},
            {code: 2016257, name: 'Kinesioterapia I', credits: 2},
            {code: 2016268, name: 'Movimiento corporal humano salud y trabajo I', credits: 2},
            {code: 2005521, name: 'Seminario ii de profundizacion', credits: 2},
            {code: 2016260, name: 'Mecánica y neuromecánica del movimiento I', credits: 2},
        {code: 25500007, name: 'Optativa de profundización II', credits: -2},
            {code: 2016223, name: 'Actividad física y deporte II', credits: 2},
            {code: 2016255, name: 'Comunidad y desarrollo humano II', credits: 2},
            {code: 2016258, name: 'Kinesioterapia II', credits: 2},
            {code: 2016261, name: 'Mecánica y neuromecánica del movimiento II', credits: 2},
            {code: 2016266, name: 'Movimiento corporal humano salud y trabajo II', credits: 2},
            {code: 2005522, name: 'Seminario iii de profundizacion', credits: 2},
        {code: 25500008, name: 'Optativa de profundización III', credits: -2},
            {code: 2016225, name: 'Actividad física y deporte III', credits: 2},
            {code: 2016256, name: 'Comunidad y desarrollo humano III', credits: 2},
            {code: 2016259, name: 'Kinesioterapia III', credits: 2},
            {code: 2016262, name: 'Mecánica y neuromecánica del movimiento III', credits: 2},
            {code: 2016267, name: 'Movimiento corporal humano salud y trabajo III', credits: 2},
            {code: 2005523, name: 'Seminario iv de profundizacion', credits: 2},
        
        # -------------------------------------- ARTES ------------------------------------
        
        #Arquitectura
        {code: 25060001, name: 'Ciudad y territorio', credits: -2},
            {code: 2017163, name: 'Análisis de ciudades', credits: 2},
            {code: 2017211, name: 'Procesos urbanos', credits: 2},
            {code: 2017170, name: 'Ciudad y movimiento moderno', credits: 2},
            {code: 2017208, name: 'Planeación ordenamiento territorial', credits: 2},
        {code: 25060002, name: 'Historia y teoria de la arquitectura', credits: -2},
        {code: 25060003, name: 'Historia y teoria de la arquitectura', credits: -2},
            {code: 2017244, name: 'Teoría de la arquitectura latinoamericana', credits: 2},
            {code: 2017178, name: 'Crítica de la arquitectura', credits: 2},
            {code: 2017167, name: 'Arquitectura y textos', credits: 2},
            {code: 2017165, name: 'Arquitectura gótica', credits: 2},
            {code: 2017246, name: 'Tratados de arquitectura', credits: 2},
        {code: 25060004, name: 'Representación', credits: -2},
            {code: 2017204, name: 'Medios artísticos', credits: 3},
            {code: 2017168, name: 'Asoleación y arquitectura', credits: 3},
            {code: 2017164, name: 'Arquitectura del paisaje', credits: 3},
        {code: 25060005, name: 'Tecnología', credits: -2},
        {code: 25060006, name: 'Tecnología', credits: -2},
        {code: 25060007, name: 'Tecnología', credits: -2},
            {code: 2017169, name: 'aspectos arquitectónicos en el diseño sismoresistente', credits: 3},
            {code: 2017171, name: 'clima y arquitectura', credits: 3},
            {code: 2017172, name: 'consolidación estructural', credits: 3},
            {code: 2017174, name: 'construcción en madera y bambú', credits: 3},
            {code: 2017177, name: 'costos y programación', credits: 3},
            {code: 2017189, name: 'especificaciones y cantidades', credits: 3},
            {code: 2017191, name: 'estructuras colgantes', credits: 3},
            {code: 2017202, name: 'interventoría', credits: 3},
            {code: 2017206, name: 'morfología estructural', credits: 3},
            {code: 2017224, name: 'residencia de obra', credits: 3},
            {code: 2017237, name: 'suelos y cimientos', credits: 3},
            {code: 2017238, name: 'tecnología del concreto', credits: 3},
            {code: 2023220, name: 'acústica', credits: 3},
            {code: 2023221, name: 'arquitectura y metal', credits: 3},
            {code: 2023225, name: 'medios digitales en construcción', credits: 3},
            {code: 2023228, name: 'origami', credits: 3},
            {code: 2023229, name: 'patologia de la edificacion', credits: 3},
        {code: 25060008, name: 'Énfasis en investigación y proyecto i', credits: -2},
            {code: 2017179, name: 'Énfasis en investigación y proyecto arquitectónico i', credits: 5},
            {code: 2017181, name: 'Énfasis en investigación y proyecto de vivienda i', credits: 5},
            {code: 2017185, name: 'Énfasis en investigación y proyecto tecnológico i', credits: 5},
            {code: 2017183, name: 'Énfasis en investigación y proyecto patrimonial i', credits: 5},
            {code: 2017187, name: 'Énfasis en investigación y proyecto urbano i', credits: 5},
        {code: 25060009, name: 'Énfasis en investigación y proyecto ii', credits: -2},
            {code: 2017180, name: 'Énfasis en investigación y proyecto arquitectónico ii', credits: 5},
            {code: 2017182, name: 'Énfasis en investigación y proyecto de vivienda ii', credits: 5},
            {code: 2017186, name: 'Énfasis en investigación y proyecto tecnológico ii', credits: 5},
            {code: 2017184, name: 'Énfasis en investigación y proyecto patrimonial ii', credits: 5},
            {code: 2017188, name: 'Énfasis en investigación y proyecto urbano ii', credits: 5},
        {code: 25060010, name: 'Seminario de investigación y proyecto i', credits: -2},
            {code: 2017230, name: 'Seminario de investigación y proyecto de vivienda i', credits: 2},
            {code: 2017232, name: 'Seminario de investigación y proyecto patrimonial i', credits: 2},
            {code: 2017226, name: 'Seminario de investigación y proyecto tecnológico i', credits: 2},
            {code: 2017227, name: 'Seminario de investigación y proyecto urbano i', credits: 2},
            {code: 2017228, name: 'Seminario de investigación y proyecto arquitectónico i', credits: 2},
        {code: 25060011, name: 'Seminario de investigación y proyecto ii', credits: -2},
            {code: 2017231, name: 'Seminario de investigación y proyecto de vivienda ii', credits: 2},
            {code: 2017233, name: 'Seminario de investigación y proyecto patrimonial ii', credits: 2},
            {code: 2017234, name: 'Seminario de investigación y proyecto tecnológico ii', credits: 2},
            {code: 2017235, name: 'Seminario de investigación y proyecto urbano ii', credits: 2},
            {code: 2017229, name: 'Seminario de investigación y proyecto arquitectónico ii', credits: 2},  
        {code: 2023230, name: 'Protocolo de trabajo de grado', credits: 2},
        {code: 2023231, name: 'Seminario trabajo de grado', credits: 2},
        {code: 25060012, name: 'Fundamentación en el contexto de las artes', credits: -2},
        {code: 25060013, name: 'Fundamentación en el contexto de las artes', credits: -2},
            {code: 2016072, name: 'Gestión cultural y empresarial en las artes', credits: 3},
            {code: 2016073, name: 'Herencias - Una mirada a la historia de las artes', credits: 3},
            {code: 2016082, name: 'Problemas contemporáneos de las artes', credits: 3},
            {code: 2016085, name: 'Responsabilidad socio-ambiental de las artes', credits: 3},
            
        #Diseño grafico
        {code: 25090001, name: 'El contexto de las artes', credits: -2},
        {code: 25090002, name: 'El contexto de las artes', credits: -2},
            {code: 2016085, name: 'Responsabilidad socio-ambiental de las artes', credits: 3},
            {code: 2016073, name: 'Herencias - Una mirada a la historia de las artes', credits: 3},
            {code: 2016082, name: 'Problemas contemporáneos de las artes', credits: 3},
        {code: 25090003, name: 'Taller de enfasis i', credits: -2},
            {code: 2016087, name: 'taller de énfasis en ilustración i', credits: 3},
            {code: 2016089, name: 'taller de énfasis en imagen fotográfica i', credits: 3},
            {code: 2016091, name: 'taller de énfasis en multimedia e imagen digital i', credits: 3},
            {code: 2016093, name: 'taller de énfasis en animación y narrativas audiovisuales i', credits: 3},
            {code: 2016095, name: 'taller de énfasis en teoría, historia y estética i', credits: 3},
            {code: 2016097, name: 'taller de énfasis en tipografía y diagramación i', credits: 3},
        {code: 25090004, name: 'Taller de enfasis ii', credits: -2},
            {code: 2016088, name: 'taller de énfasis en ilustración ii', credits: 3},
            {code: 2016090, name: 'taller de énfasis en imagen fotográfica ii', credits: 3},
            {code: 2016092, name: 'taller de énfasis en multimedia e imagen digital ii', credits: 3},
            {code: 2016094, name: 'taller de énfasis en animación y narrativas audiovisuales ii', credits: 3},
            {code: 2016096, name: 'taller de énfasis en teoría, historia y estética ii', credits: 3},
            {code: 2016098, name: 'taller de énfasis en tipografía y diagramación ii', credits: 3},
            
        #Diseño industrial
        {code: 25100001, name: 'Tecnología - Materiales y procesos', credits: -2},
            {code: 2017327, name: 'Materiales compuestos', credits: 2},
            {code: 2017342, name: 'Procesos avanzados de manufactura', credits: 2},
        {code: 25100002, name: 'Cultura - Humano', credits: -2},
            {code: 2017310, name: 'Diseño, cultura y sociedad', credits: 2},
            {code: 2017326, name: 'Macro Ergonomía', credits: 2},
            {code: 2024278, name: 'Laboratorio de Ergonomía', credits: 2},
        {code: 25100003, name: 'Cultura - Ambiente', credits: -2},
            {code: 2017335, name: 'Perfil Ambiental', credits: 2},
            {code: 2017343, name: 'Producción más Limpia', credits: 2},
            {code: 2017345, name: 'Sistemas de Gestión Ambiental', credits: 2},
        {code: 25100004, name: 'Cultura - Pensamiento, historia y teoría', credits: -2},
            {code: 2017306, name: 'Cultura Material y del Arte en América Latina', credits: 2},
            {code: 2017346, name: 'Taller de Crítica Experimental', credits: 2},
            {code: 2024277, name: 'Teoría Morfológica', credits: 2},
        {code: 25100005, name: 'Observatorio de Diseño', credits: -2},
        {code: 25100006, name: 'Observatorio de Diseño', credits: -2},
        {code: 25100007, name: 'Observatorio de Diseño', credits: -2},
            {code: 2017330, name: 'observatorio de diseño i', credits: 4},
            {code: 2017331, name: 'observatorio de diseño ii', credits: 4},
            {code: 2017332, name: 'observatorio de diseño iii', credits: 4},
            {code: 2017333, name: 'observatorio de diseño iv', credits: 4},
            {code: 2024273, name: 'observatorio de diseño v', credits: 4},
            {code: 2024274, name: 'observatorio de diseño vi', credits: 4},
            {code: 2024275, name: 'observatorio de diseño vii', credits: 4},
            {code: 2024605, name: 'observatorio de diseño viii', credits: 8},
        {code: 25100008, name: 'Cultura - Comunicación', credits: -2},
            {code: 2017329, name: 'Multimedia - Medios Interactivos Digitales', credits: 2},
            {code: 2017328, name: 'Modelación Avanzada', credits: 2},
            {code: 2024276, name: 'Diseño de exposiciones', credits: 2},
        {code: 25100009, name: 'Tecnología - Organización', credits: -2},
            {code: 2017311, name: 'Economía e Industria', credits: 2},
            {code: 2017347, name: 'Tecnología Avanzada', credits: 2},
            {code: 2017307, name: 'Dirección Organizacional', credits: 2},
        {code: 25100010, name: 'Fundamentos en el contexto de las artes', credits: -2},
        {code: 25100011, name: 'Fundamentos en el contexto de las artes', credits: -2},
            {code: 2016073, name: 'Herencias - Una mirada a la historia de las artes', credits: 3},
            {code: 2016085, name: 'Responsabilidad socio-ambiental de las artes', credits: 3},
            {code: 2016082, name: 'Problemas contemporáneos de las artes', credits: 3},
            {code: 2016072, name: 'Gestión cultural y empresarial en las artes', credits: 3},
        
        # -------------------------------------- MEDICINA VETERINARIA Y DE ZOOTECNIA  ------------------------------------
        
        #Zootecnia
        {code: 25560001, name: 'Matemáticas', credits: -2},
            {code: 2025808 , name: 'Algebra lineal aplicada a ciencias animales', credits: 4},
        {code: 25560002, name: 'Biología', credits: -2},
        {code: 25560003, name: 'Biología', credits: -2},
        {code: 25560004, name: 'Estadística', credits: -2},
        {code: 25560005, name: 'Economía', credits: -2},
            {code: 2017142, name: 'Principios de economía agrícola', credits: 3},
            {code: 2017115, name: 'Economía de la producción agropecuaria', credits: 3},
        {code: 25560006, name: 'Optativa de área', credits: -2},
        {code: 25560007, name: 'Optativa de área', credits: -2},
        {code: 25560008, name: 'Optativa de área', credits: -2},
            {code: 2017080, name: 'planeación y evaluación de empresas agropecuarias', credits: 2},
            {code: 2017098, name: 'administración financiera de agronegocios', credits: 3},
            {code: 2017101, name: 'agronegocios internacionales', credits: 3},
            {code: 2017103, name: 'alimentación de monogástricos', credits: 3},
            {code: 2017104, name: 'alimentación de rumiantes', credits: 3},
            {code: 2017109, name: 'biotecnología animal', credits: 3},
            {code: 2017111, name: 'citogenética', credits: 3},
            {code: 2017112, name: 'clasificación y juzgamiento', credits: 3},
            {code: 2017113, name: 'control de calidad de alimentos concentrados', credits: 3},
            {code: 2017116, name: 'evaluación de forrajes', credits: 3},
            {code: 2017117, name: 'evaluación genética', credits: 3},
            {code: 2017118, name: 'fisiología aplicada a la digestión', credits: 3},
            {code: 2017119, name: 'fisiología aplicada a la lactancia', credits: 3},
            {code: 2017120, name: 'fisiología aplicada al control de la reproducción', credits: 3},
            {code: 2017121, name: 'fisiología aplicada al crecimiento', credits: 3},
            {code: 2017122, name: 'fisiología de peces', credits: 3},
            {code: 2017127, name: 'introducción a la ciencia y tecnología de alimentos', credits: 3},
            {code: 2017128, name: 'manejo de praderas', credits: 3},
            {code: 2017129, name: 'mejoramiento animal aplicado', credits: 3},
            {code: 2017131, name: 'mejoramiento de forrajes', credits: 3},
            {code: 2017132, name: 'mercadeo agropecuario', credits: 3},
            {code: 2017136, name: 'nutrición general de peces', credits: 3},
            {code: 2017139, name: 'nutrición y alimentación de especies silvestres', credits: 3},
            {code: 2017144, name: 'reproducción de peces', credits: 3},
            {code: 2024376, name: 'planeación y evaluación de proyectos agroempresariales', credits: 3},
        {code: 25560009, name: 'Producción', credits: -2},
        {code: 25560010, name: 'Producción', credits: -2},
            {code: 2017145, name: 'sistemas de producción de bovinos de doble propósito', credits: 3},
            {code: 2017147, name: 'sistemas de producción apícola', credits: 3},
            {code: 2017150, name: 'sistemas de producción de bovinos de carne', credits: 3},
            {code: 2017151, name: 'sistemas de producción de bovinos de leche', credits: 3},
            {code: 2017152, name: 'sistemas de producción de equinos', credits: 3},
            {code: 2017153, name: 'sistemas de producción de especies menores', credits: 3},
            {code: 2017154, name: 'sistemas de producción de especies silvestres', credits: 3},
            {code: 2017155, name: 'sistemas de producción de mascotas', credits: 3},
            {code: 2017156, name: 'sistemas de producción de pequeños rumiantes', credits: 3},
            {code: 2024452, name: 'sistemas de producción de peces ornamentales (agua dulce)', credits: 3}
 
]) 

# *************************************************************************
