# ***************************** Lista de Materias***********************************

Subject.create([
        
         # -------------------------------------- CIENCIAS ECONOMICAS ------------------------------------
        
        #Administración de empresas
        {code: 25200001, name: 'Formación Básica', credits: -2},
        {code: 25200002, name: 'Estadística y Probabilidad fundamental', credits: -2}, 
        {code: 25200003, name: 'Econometría(sugerida)', credits: -2},
        {code: 25200004, name: 'Interdisciplinar 1', credits: -2},
        {code: 25200005, name: 'Interdisciplinar 2', credits: -2},
        {code: 25200006, name: 'Interdisciplinar 3', credits: -2},
            {code: 2016123, name: 'instituciones politico-constitucionales colombianas', credits: 4},
            {code: 2016043, name: 'Matemáticas financieras', credits: 4},
            {code: 1000015, name: 'Probabilidad fundamental', credits: 3},
            {code: 1000016, name: 'Inferencia estadística fundamental', credits: 3},
            {code: 2016125, name: 'Métodos cuantitativos', credits: 4},
            {code: 2016119, name: 'Derecho internacional', credits: 3},
            {code: 2016124, name: 'Investigación operativa', credits: 3},
            {code: 2016126, name: 'Planeación estratégica', credits: 3},
            {code: 2015411, name: 'Tipos modernos de contratación', credits: 3},
            {code: 2016358, name: 'Gerencia de recursos humanos', credits: 3},
            {code: 2016587, name: 'Competitividad, productividad y benchmarking', credits: 3},
            {code: 2017865, name: 'Desarrollo humano en el trabajo', credits: 3},
            {code: 2017872, name: 'Entrevista psicológica', credits: 3},
            {code: 2017911, name: 'Psicología organizacional', credits: 3},
            {code: 2021835, name: 'Investigación de mercados', credits: 3},
            {code: 2006824, name: 'Contabilidad de inversiones y financiación', credits: 4},
            {code: 2006838, name: 'Control interno y gestion', credits: 3},
            {code: 2006871, name: 'Investigación operativa', credits: 3},
            {code: 2006926, name: 'Planeación estratégica', credits: 4},
            {code: 2006966, name: 'Pensamiento económico', credits: 4},
            {code: 2019594, name: 'Microeconomía ii', credits: 3},
            {code: 2022104, name: 'Asignatura genérica', credits: 3},
            {code: 2023780, name: 'Macroeconomía ii', credits: 4},
            {code: 2006973, name: 'Economía política i', credits: 3},
            {code: 2006979, name: 'Microeconomía ii', credits: 4},
            
            
        #Economia
        {code: 25220001, name: 'Contenido cuantitativo', credits: -2},
        {code: 25220002, name: 'Interdisciplinar - profesional 1', credits: -2},
        {code: 25220003, name: 'Interdisciplinar - profesional 2', credits: -2},
        {code: 25220004, name: 'Interdisciplinar - profesional 3', credits: -2},
        {code: 25220005, name: 'Interdisciplinar - profesional 4', credits: -2},
            {code: 2016000, name: 'derecho finaciero', credits: 3},
            {code: 2016027, name: 'derecho laboral', credits: 4},
            {code: 2016030, name: 'economía dinámica en matlab', credits: 3},
            {code: 2016031, name: 'economía evolucionista y herramientas de simulación', credits: 3},
            {code: 2016034, name: 'economía y política social', credits: 3},
            {code: 2016035, name: 'estado y descentralización', credits: 3},
            {code: 2016040, name: 'gestión y política pública', credits: 3},
            {code: 2016043, name: 'matemáticas financieras', credits: 4},
            {code: 2016044, name: 'mercadeo internacional', credits: 3},
            {code: 2016045, name: 'mercado de capitales y banca de inversión', credits: 3},
            {code: 2016047, name: 'modelos económicos computacionales', credits: 3},
            {code: 2016048, name: 'nueva economía política', credits: 3},
            {code: 2016049, name: 'política fiscal avanzada', credits: 3},
            {code: 2016050, name: 'seminario de gestión de negocios internacionales', credits: 3},
            {code: 2016051, name: 'seminario de historia económica de colombia', credits: 3},
            {code: 2016052, name: 'sistema monetario y crisis financiera internacional', credits: 3},
            {code: 2016054, name: 'tópicos de econometría ii', credits: 3},
            {code: 2016055, name: 'tópicos de econometría i', credits: 3},
            {code: 2016109, name: 'programación dinámica', credits: 3},
            {code: 2018392, name: 'economia del conocimiento o nueva economia', credits: 3},
            {code: 2021788, name: 'evaluacion economica y social de proyectos', credits: 3},
            {code: 2024037, name: 'estructuras de mercado y competencia perfecta en la historia del pensamiento economico', credits: 3},
            {code: 2024267, name: 'globalización e integración con énfasis en asia pacifico', credits: 3},
            {code: 2024564, name: 'econometria financiera', credits: 3},
            {code: 2024565, name: 'regulacion y mercados', credits: 3},
            {code: 2024566, name: 'evaluacion economica y social de proyectos', credits: 3},
            {code: 2024567, name: 'economia, politica y conflicto', credits: 3},
            {code: 2024569, name: 'aplicaciones empíricas de la teoría del consumidor', credits: 3},
            {code: 2024572, name: 'topicos de politica publica', credits: 3},
            {code: 2024575, name: 'keynesian economics', credits: 3},
            {code: 2024595, name: 'historia economica de america latina', credits: 3},
            {code: 2024665, name: 'dinero y mercados financieros', credits: 3},
            {code: 2024666, name: 'integracion y bloques economicos', credits: 3},
            {code: 2024667, name: 'economia y política de la sostenibilidad', credits: 3},
            {code: 2024653, name: 'alternativas al desarrollo', credits: 3},
            {code: 2024568, name: 'ciclos economicos', credits: 3},
            {code: 2024570, name: 'economia de los grupos economicos ii', credits: 3},
            {code: 2024571, name: 'seminario economia constitucional', credits: 3},
            {code: 2024573, name: 'ocupacion, empleo y seguridad social', credits: 3},
            {code: 2024574, name: 'internacionalizacion y cambio estructural', credits: 3},
            {code: 2024576, name: 'financiarizacion en la economia mundial', credits: 3},
            {code: 2024577, name: 'desarrollo economia y libertad', credits: 3},
            {code: 2024578, name: 'fundamentos de teoría económica ambiental', credits: 3},
            {code: 2024579, name: 'la ciudad: reflexiones socioeconomicas sobre la espacialidad urbana', credits: 3},
            {code: 2024596, name: 'economia de los grupos economicos', credits: 3},
            
            
            
            
        # -------------------------------------- CIENCIAS  ------------------------------------
        
        #Ciencias de la computación
        {code: 29330001, name: 'Física', credits: -2},
            {code: 2022689, name: 'Fundamentos de fisica', credits: 3},
        {code: 29330002, name: 'Criptografía e información', credits: -2},
            {code: 2027311, name: 'Introducción a la criptografía y a la teoría de información', credits: 3},
            {code: 2027310, name: 'Criptografía', credits: 3},
        {code: 29330003, name: 'Analisis númerico y mátematica aplicada', credits: -2},
            {code: 2027628, name: 'Teoría de lenguajes formales', credits: 3},
            {code: 2019267, name: 'Teoría de la recursión', credits: 3},
            {code: 2021834, name: 'Informática aplicada', credits: 3},
            {code: 2024065, name: 'Mundos Virtuales', credits: 3},
        {code: 29330004, name: 'Computación cientifica', credits: -2},
            {code: 2015173, name: 'Introducción a la optimización', credits: 4},
            {code: 2027630, name: 'Introducción al modelamiento matemático', credits: 3},
        {code: 29330005, name: 'Computación aplicada', credits: -2},
            {code: 2027641, name: 'Análisis de bases de datos', credits: 3},
            {code: 2025196, name: 'Introducción a la biología computacional', credits: 4},
            {code: 2027631, name: 'Introducción a la inteligencia artificial', credits: 3},
            {code: 2027309, name: 'Análisis forense digital', credits: 4},
            {code: 2027632, name: 'Física computacional', credits: 3},
            {code: 2027643, name: 'Introducción al aprendizaje de máquina', credits: 3},
            {code: 2016740, name: 'Finanzas Computacionales', credits: 4},
        
        #Matematicas
        {code: 25180001, name: 'Geometria', credits: -2},
            {code: 2015172, name: 'Geometría elemental', credits: 4},
            {code: 1000008, name: 'Geometria Vectorial y Analítica', credits: 4},
        {code: 25180002, name: 'Física', credits: -2},    
            {code: 2015170, name: 'Fundamentos de oscilaciones, ondas y óptica', credits: 4},
            {code: 2015169, name: 'Fundamentos de mecánica de fluidos', credits: 3},
            {code: 2015167, name: 'Fundamentos de física moderna', credits: 3},
        {code: 25180003, name: 'Disciplinar 1', credits: -2},
        {code: 25180004, name: 'Disciplinar 2', credits: -2},
        {code: 25180005, name: 'Disciplinar 3', credits: -2},
            {code: 2015160, name: 'Algebra conmutativa', credits: 4}, 
            {code: 2015179, name: 'Procesos estocásticos', credits: 4},
            {code: 2015161, name: 'Análisis estocástico', credits: 4},
            {code: 2015164, name: 'Ecuaciones diferenciales parciales', credits: 4},
            {code: 2015165, name: 'Epistemología e historia de la matemática', credits: 4},
            {code: 2015171, name: 'Geometría diferencial', credits: 4},
            {code: 2015177, name: 'Modelos matemáticos', credits: 4},
            {code: 2015182, name: 'Teoria de conjuntos', credits: 4},
            {code: 2015183, name: 'Teoría de ecuaciones diferenciales ordinarias', credits: 4},
            {code: 2015185, name: 'Teoría de modelos', credits: 4},
            {code: 2015186, name: 'Teoría de números', credits: 4},
            {code: 2025580, name: 'Anillos y módulos', credits: 4},
            
            
            
         # -------------------------------------- INGENIERÍA   ------------------------------------
        #Ingeniería mecatronica
        {code: 25480001, name: 'Física', credits: -2},
            {code: 1000018, name: 'Fundamentos de física moderna', credits: 3},
        {code: 25480002, name: 'Procesos de Manufactura', credits: -2},
        {code: 25480003, name: 'Herramientas para ingeniería', credits: -2},
            {code: 2015942, name: 'Aplicaciones de elementos finitos', credits: 3},
        {code: 25480004, name: 'Ciencias económicas y administrativas', credits: -2},
        {code: 25480005, name: 'Herramientas para automatización de procesos', credits: -2},
            {code: 2022888, name: 'Técnicas de control', credits: 3},
            {code: 2017290, name: 'Técnicas de Inteligencia Artificial', credits: 3},
            
        #Ingeniería quimica
        {code: 25490002, name: 'Informatica y comunicación', credits: -2},
            {code: 2015709, name: 'Comunicación Oral y Escrita', credits: 3},
        {code: 25490003, name: 'Termodinámica', credits: -2},
            {code: 2015738, name: 'Termodinámica de Ciclos', credits: 3},
            {code: 2015739, name: 'Termodinámica molecular', credits: 3},
        {code: 25490004, name: 'Simulación', credits: -2},
            {code: 2015728, name: 'Modelamiento y Simulación de Procesos Bioquímicos', credits: 3},
            {code: 2015729, name: 'Modelamiento y simulación de procesos químicos', credits: 3},
        {code: 25490005, name: 'Materiales', credits: -2},
            {code: 2015717, name: 'Introducción a la ingeniería de materiales', credits: 3},
            {code: 2015724, name: 'Laboratorio de operaciones unitarias ii', credits: 3},
            {code: 2015727, name: 'Materiales', credits: 3},
            {code: 2015730, name: 'Nuevos tópicos en ingeniería quimica', credits: 3},
            {code: 2024929, name: 'Introducción a la ingeniería de materiales poliméricos', credits: 3},
            {code: 2015598, name: 'Química de Sólidos', credits: 3},
            {code: 2001798, name: 'Procesos quimicos i', credits: 3},
        {code: 25490001, name: 'Administración de empresas', credits: -2},
            {code: 2015694, name: 'Derecho laboral', credits: 3},
            {code: 2015698, name: 'Administración de empresas', credits: 3},
            {code: 2015699, name: 'Administración de mercados', credits: 3},
            {code: 2015700, name: 'Fundamentos de contabilidad financiera', credits: 3},
            {code: 2015704, name: 'Mercadeo internacional', credits: 3},
            {code: 2015705, name: 'Mercados I', credits: 4},
            
        # -------------------------------------- MEDICINA   ------------------------------------    
        
        #Fisioterapia
        {code: 25500001, name: 'Biologia', credits: -2},
        {code: 25500002, name: 'Quimica', credits: -2},
        {code: 25500003, name: 'Ciencias sociales y humanas', credits: -2},
        {code: 25500004, name: 'Ciencias sociales y humanas', credits: -2},
            {code: 2017502, name: 'Procesos comunitarios', credits: 3},
            {code: 2017903, name: 'Psicología Comunitaria', credits: 3},
            {code: 2017914, name: 'Psicología y Salud Ocupacional', credits: 3},
            {code: 2024774, name: 'Medicina Social y Salud Colectiva: fundamentos conceptuales', credits: 3},
        {code: 25500005, name: 'Optativa profesional', credits: -2},
            {code: 2016242, name: 'Epidemiología social', credits: 2},
            {code: 2016263, name: 'Mi cuerpo, sus cuerpos, nuestros cuerpos', credits: 2},
            {code: 2016289, name: 'Manejo del dolor', credits: 2},
            {code: 2016292, name: 'Música y bienestar ocupacional', credits: 2},
            {code: 2016294, name: 'Potenciales evocados', credits: 3},
            {code: 2016296, name: 'Reflexiones entorno al proceso de envejecimiento', credits: 3},
            {code: 2016298, name: 'Bioseguridad', credits: 2},
            {code: 2016300, name: 'Investigación biomédica y social', credits: 3},
            {code: 2017939, name: 'Primeros auxilios', credits: 2},
            {code: 2021165, name: 'Ingenieria tisular', credits: 2},
            {code: 2022175, name: 'Cuerpo e imagen', credits: 3},
            {code: 2022733, name: 'Iniciacion a estudios feministas y de género', credits: 3},
            {code: 2022841, name: 'Fundamentación y practica en salud de los trabajadores', credits: 4},
            {code: 2023478, name: 'Contexto bioseguridad', credits: 2},
        {code: 25500006, name: 'Optativa de profundización I', credits: -2},
            {code: 2016221, name: 'Actividad física y deporte I', credits: 2},
            {code: 2016254, name: 'Comunidad y desarrollo humano I', credits: 2},
            {code: 2016257, name: 'Kinesioterapia I', credits: 2},
            {code: 2016268, name: 'Movimiento corporal humano salud y trabajo I', credits: 2},
            {code: 2005521, name: 'Seminario ii de profundizacion', credits: 2},
            {code: 2016260, name: 'Mecánica y neuromecánica del movimiento I', credits: 2},
        {code: 25500007, name: 'Optativa de profundización II', credits: -2},
            {code: 2016223, name: 'Actividad física y deporte II', credits: 2},
            {code: 2016255, name: 'Comunidad y desarrollo humano II', credits: 2},
            {code: 2016258, name: 'Kinesioterapia II', credits: 2},
            {code: 2016261, name: 'Mecánica y neuromecánica del movimiento II', credits: 2},
            {code: 2016266, name: 'Movimiento corporal humano salud y trabajo II', credits: 2},
            {code: 2005522, name: 'Seminario iii de profundizacion', credits: 2},
        {code: 25500008, name: 'Optativa de profundización III', credits: -2},
            {code: 2016225, name: 'Actividad física y deporte III', credits: 2},
            {code: 2016256, name: 'Comunidad y desarrollo humano III', credits: 2},
            {code: 2016259, name: 'Kinesioterapia III', credits: 2},
            {code: 2016262, name: 'Mecánica y neuromecánica del movimiento III', credits: 2},
            {code: 2016267, name: 'Movimiento corporal humano salud y trabajo III', credits: 2},
            {code: 2005523, name: 'Seminario iv de profundizacion', credits: 2}
        
            
]) 
# *************************************************************************
