development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: "ataraxiasedundnes@gmail.com"
  :password: "sedUNdnesataraxia90"
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: "ataraxiasedundnes@gmail.com"
  :password: "sedUNdnesataraxia90"
  :enable_starttls_auto: true