# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 825f32936aa3cc5c45884d60a97357988c3c06cf137eacd0a57726fdeee8b3d29d7e6bc1be5f58673f9c2494e2ae263b27fa236f501f1229864059b7ab70a003

test:
  secret_key_base: b2e2a732039acb07f408e628db6a97f0f93e5504818e2cc2c6932041dc3463af97bf697702667e938bdfb5590e4957edd11ac0d459f1799dacdf5beea6452c27

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>