# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/


modal = document.getElementById('myModal')
# Get the button that opens the modal
btn = document.getElementById('addB')
# Get the <span> element that closes the modal
span = document.getElementsByClassName('close')[0]
# When the user clicks the button, open the modal 

btn.onclick = ->
  alert 'hoooola'
  modal.style.display = 'block'
  return

# When the user clicks on <span> (x), close the modal

span.onclick = ->
  modal.style.display = 'none'
  return

# When the user clicks anywhere outside of the modal, close it

window.onclick = (event) ->
  if event.target == modal
    modal.style.display = 'none'
  return

# ---
# generated by js2coffee 2.2.0